sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: S6JZwDHlNxiyAx9f2SnrOb8gyrSTSHYH748COSw2tXJaeOdsJ7DM1W29lHsbYQpfn7kFEO2KK8zzcSfKjtwVUcdWDJD3l1rWl9+klPD5IiPzq85j8vf8b+bDnWg49sI3wrQKruNVDnjn3pm2IIACEoZ4MUxOcsn8yjjbaErLfc/sAR+ayEF6uXaHb1afoOi7+QeS/GNWnOY5woDFuqbHmdXqXXBgPY0aiIbyiunRyQJvH5WSoOlfbzX5qvSgInQfhC9vYl5hACV/gFfVlG7hiChFJoC8Fg/WDd0VU0Jb9YUotsF0ht2Ryn5rPKUtqhhGJVsolb6Vzt8+GshzQzSI84pK/F/lRcMKeX6iCziTZ2fn0rVOyWwyyT2LdRBSZpgxZxPMipHEkAvnfwDZtcV3u1alFFybMlYC4Hh9yX+hgmqurFSfu1nq/tHX47GiKWJ31G8VRtNRzV/jVWFHovd2fsFoZELrtItJDAKyRulaFXJw4KcguaQqVi4xQ7W9eLX0Y9SdtVFUJ+I8PLGZsodXRejFP5qN/11u2v3N3WXfoA3HMsI7BgkKswjJRqfKNPNq9VHzPSmEVFDJfbFrnEP4Y4MYbPdAFYcaUrc/wd1Nu1n8jlg9K5g1hUtsfsrxODDTxbNbrh70y7CGLB4p5CQ5/JVDpbyyZ53uHMLvVDTr0w8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Ne-er-Do-Well_5405
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy